=
poetry.lock

fix: update poetry dependency file

Poetry setup

---

poetry.lock
src/bthome_ble/parser.py

fix: code format

---

poetry.lock
pyproject.toml
src/bthome_ble/const.py
src/bthome_ble/parser.py
tests/test_parser.py

add support for new sensor types moisture, count, mass (kg and lbs) and dew point
add b-parasite as manufacturer
ToDo

feat: add new sensor types

---

poetry.lock
pyproject.toml
src/bthome_ble/const.py
src/bthome_ble/parser.py
tests/test_parser.py

This PR adds support for binary sensors to BTHome

feat: add binary sensors

---

poetry.lock
src/bthome_ble/const.py
src/bthome_ble/event.py
src/bthome_ble/parser.py
tests/test_parser.py

- adding support for events, see https://github.com/home-assistant/bthome.io/issues/5
- adding support for 1 byte humidity and moisture measurements with factor 1, see https://github.com/rbaron/b-parasite/issues/59

Add support for events

---

src/bthome_ble/parser.py
tests/test_parser_v2.py

Adding support for multiple measurements of the same type (fixes https://github.com/home-assistant/bthome.io/issues/7)
Will work both with bthome V1 and V2.

Multiple measurements of the same type

---

src/bthome_ble/parser.py
tests/test_parser_v1.py
tests/test_parser_v2.py

fix: parser not parsing multiple uuids

---

poetry.lock
pyproject.toml
src/bthome_ble/const.py
src/bthome_ble/parser.py
tests/test_parser_v2.py

This PR adds the following sensors
- Rotation in °: 2 bytes SINT, factor 0.1, Range -3276.8° to -3276.8° (such that we at least cover +/-360°)
- Distance in mm: 2 bytes UINT, factor 1, Range 0-65535 mm
- Distance in m: 2 bytes. UINT, factor 0.1, Range 0-6553.5 m
- Time in seconds: 3 bytes UINT, unit s (second), factor 0.001, Range 0-16777.215 s
- Current in Ampere: 2 bytes UINT, factor 0.001, Range 0-65.535 A
- Speed in m/s: 2 bytes UINT, factor 0.01, Range 0-655.35 m/s
Fix for #22
**ToDo**

feat: new sensors

---

poetry.lock
src/bthome_ble/const.py
tests/test_parser_v2.py

**New/changed Sensors**
- UV Index (requested in #22)
- Change Time sensor to Duration sensor (in seconds) (similar in Home Assistant, duration is in seconds, time is a timestamp)
- Temperature with one digit (requested on the [HA forum](https://community.home-assistant.io/t/bluetooth-bthome-atc-mithermometer-decimal-places/465172/35)

UV Index and Duration sensor

---

poetry.lock
src/bthome_ble/const.py
tests/test_parser_v1.py
tests/test_parser_v2.py

Add the following sensors
- Packet Id (only meant for packet filtering) (fix for #34)
- Volume (unit: Liters) (fix for #33)
- Volume (unit: milliliters)
- Volume Flow Rate (unit: m3/hour)

feat: volume (flow rate) and packet id support

---

=2.13.0
poetry.lock
pyproject.toml

fix: bump sensor-state-data

---

src/bthome_ble/const.py
tests/test_parser_v2.py

feat: add voltage with 1 digit (fix for #39)

feat: add voltage with 1 digit

---

src/bthome_ble/parser.py

fix: correct data length check

fix: correct data length check

---

.github/workflows/ci.yml
.pre-commit-config.yaml
poetry.lock
pyproject.toml
src/bthome_ble/parser.py
tests/test_parser_v2.py

fix: parse objects of the same time correctly (fix for #46)

fix: parse objects of the same time correctly

---

.flake8
src/bthome_ble/parser.py
tests/test_parser_v2.py

feat: add possibility to include mac in payload (fix for #42)

feat: add possibility to include mac in payload

---

src/bthome_ble/const.py
tests/test_parser_v2.py

feat: add gas sensor

---

CONTRIBUTING.md
poetry.lock
pyproject.toml
src/bthome_ble/const.py
tests/test_parser_v2.py

- feat: add water sensor (fix for #56)
- fix: small documentation update

feat: add water sensor

---

src/bthome_ble/const.py
src/bthome_ble/parser.py
tests/test_parser_v2.py

- add sleepy sensors list for sensors that most likely do not send data regularly
- add shelly sensor names

feat: add sleepy sensors

---

src/bthome_ble/__init__.py

fix: add sleepy sensors to init

fix: add sleepy sensors to init

---

src/bthome_ble/parser.py

add "trigger based device" to device type

fix: add trigger based device to device type

---

src/bthome_ble/parser.py

fix: revert trigger based device name

fix: revert trigger based device name

---

tests/test_parser_v2.py

fix: fix failing tests

---

.github/workflows/ci.yml

fix: bump semantic release

---

src/bthome_ble/const.py
src/bthome_ble/parser.py
tests/test_parser_v2.py

As requested in #89 adding a raw sensor that reports back the raw data.

feat: add raw hex sensor

---

src/bthome_ble/parser.py
tests/test_parser_v2.py

fix: fix counter verification (fix for #99)

fix: fix counter verification

---

src/bthome_ble/event.py
tests/test_parser_v2.py

feat: add button hold event

---

.github/workflows/ci.yml

fix: bump python-semantic-release

fix: bump python-semantic-release

---

.github/workflows/ci.yml

fix: fix release workflow

---

.github/workflows/ci.yml

fix: fix pypi workflow

---

.github/workflows/ci.yml

fix: reference to gh action pypi push

fix: reference to gh action pypi push

---

pyproject.toml

fix: use list for version_toml

fix: use list for version_toml

---

.github/workflows/ci.yml

fix: rename pypi token

---

.github/workflows/ci.yml

fix: allow contents permission to workflow

fix: allow contents permission to workflow

---

src/bthome_ble/const.py
tests/test_parser_v2.py

feat(conductivity): add 0x56 for 16-bit Conductivity measurement type

---

src/bthome_ble/const.py
tests/test_parser_v2.py

feat: add new sensors
feat: add 1 byte temperature sensors (fix #111)
feat: add negative count and power sensors (fix #134)
feat: add negative current sensor (fix #135)

feat: add new sensors

---

.github/workflows/ci.yml
commitlint.config.mjs

(feat): update lint and commitlint

chore: update lint and commitlint

---

src/bthome_ble/parser.py
tests/test_parser_v1.py
tests/test_parser_v2.py

https://github.com/Bluetooth-Devices/bthome-ble/pull/227

fix: update service info imports to use habluetooth

---

src/bthome_ble/const.py
tests/test_parser_v2.py

- fixed precipitation multiplier to 0.1

feat(precipitation): correct precipitation multiplier
