src/bthome_ble/parser.py
Use guard clauses by turning if-statements that span most of the rest of the code into `if not X: continue`.
=> Simplify parsing using guard clauses

src/bthome_ble/const.py
fix: remove update binary sensor as it can't be used in home assistant
=> fix: remove update binary sensor

src/bthome_ble/parser.py
Remove `device_info_available` flag
We can add some `device_info_available` flag later, or call it a `passive_only` flag, once we add GATT characteristic support.
=> Remove device info available flag

src/bthome_ble/bthome_v1_encryption.py, src/bthome_ble/bthome_v2_encryption.py, src/bthome_ble/const.py, src/bthome_ble/parser.py, tests/test_parser_v2.py, tests/test_v1_encryption.py, tests/test_v2_encryption.py
Remove object format and length byte
To safe bytes, this PR removes the object format and length byte and will use a fixed format and length for each measurement type. 
ToDo
=> Remove object format length byte

src/bthome_ble/const.py, src/bthome_ble/event.py, src/bthome_ble/parser.py, tests/test_parser_v1.py, tests/test_parser_v2.py
As proposed in https://github.com/home-assistant/bthome.io/issues/5#issuecomment-1285504858 this PR removes the switch events and changes the evens for buttons and dimmers. 
Button --> events (press, single press, double press, triple press, long press, double long press, triple long press)
Dimmer --> events (rotate right x steps, rotate left x steps)
Also added the option to broadcast "no event", which you will need in case you have a triple button device, and only want to send an event with e.g. the 2nd and 3rd button. As the order of button 1, 2 an 3 has to be the same in each message, it will be required to send "no event (None)" for the first button.
=> Button and dimmer events

src/bthome_ble/parser.py, tests/test_parser_v2.py
I ran into the "problem" that the current implementation for multiple measurements of the same type (e.g. 3 temperatures), will result in three devices (1, 2 and 3) in Home Assistant. This is caused by the fact that I had defined one device_id per temperature. However, this is more meant for thinks like an indoor and outdoor temperature device that report via the indoor device.  
I now have changed it such that we always have one device (`device_id = None`). Each measurement will get a postfix, in case there are more than one of that type. E.g. temperature_1, temperature_2 etc, with name Temperature 1, Temperature 2, etc.
=> fix: multiple measurements fix

src/bthome_ble/bthome_v2_encryption.py, src/bthome_ble/parser.py, tests/test_parser_v2.py, tests/test_v2_encryption.py
As discussed in #20, this PR proposes to remove the `cipher.update(b"\x11")` in the decryption code for BTHome V2. This will remove the need to apply this in the sensor firmware code as well. 
In V1, this `cipher.update(b"\x11")` will be remained as it was, to keep backward compatibility. V2 isn't used most likely at the moment, as Home Assistant will be updated in the December release with V2 support.
=> feat: remove cipher update

src/bthome_ble/bthome_v2_encryption.py, src/bthome_ble/parser.py
Fix for warning for numerical order object id. Check was reversed.
Updated the encryption example to be in line with the documentation
=> fix: warning for numerical order object id

src/bthome_ble/const.py, tests/test_parser_v2.py
Add sensors for water/gas/electricity meters with 4 bytes (factor 0.001). 
- Volume (e.g. water meter)
- Energy
- Gas
This PR fixes #52
=> feat: add gas water energy meter

.github/workflows/ci.yml, .pre-commit-config.yaml, poetry.lock, pyproject.toml, src/bthome_ble/const.py, src/bthome_ble/parser.py, tests/test_parser_v1.py, tests/test_parser_v2.py
add new sensor types
- timestamp
- acceleration (m/s^2)
- gyroscope (°/s)
fix for KeyError with Shelly BLU button (https://github.com/home-assistant/core/issues/92758)
=> feat: timestamp acceleration and gyroscope

src/bthome_ble/parser.py, tests/test_parser_v2.py
fix: decryption bug fixed
fix for https://github.com/home-assistant/core/issues/94524
In the decryption process, the BTHome Device Information byte was hardcoded to set it to `x41`, even when a device had specified something different. E.g. the Shelly BLU button is using `x45`, as it is a non-regular updating device. As a result, decryption always failed when not using `x41`. This is now fixed.
=> fix: decryption bug fixed

src/bthome_ble/parser.py, tests/test_parser_v2.py
BREAKING CHANGE: the bindkey should no longer be set directly on the object, call `set_bindkey` instead
=> feat: add ability to set the bind key after init

src/bthome_ble/const.py, src/bthome_ble/parser.py, tests/test_parser_v2.py
This PR adds a text sensor (fix for #74). 
This data object for a text sensor is variable in size, therefore, the first byte after the byte with the object will have to specify the length of the text. The encoding of the text string should be UTF-8. 
Example
`\x44\x53\x0C\x48\x65\x6C\x6C\x6F\x20\x57\x6F\x72\x6C\x64\x21`
`\x44` = BTHome Device Information
`\x53` = Object id for a text sensor
`\x0C` = Length of the text (12 characters)
`\x48\x65\x6C\x6C\x6F\x20\x57\x6F\x72\x6C\x64\x21` = Text `Hello World!`
=> feat: add text sensor

src/bthome_ble/parser.py
`datetime.utcfromtimestamp` will be deprecated in Python 3.12
https://docs.python.org/3.12/library/datetime.html#datetime.datetime.utcfromtimestamp
=> fix: replace datetime.utcfromtimestamp

src/bthome_ble/parser.py
fix: no check of encryption counter when bindkey has not been verified
=> fix: no check of encryption counter when bindkey has not been verified

src/bthome_ble/const.py, tests/test_parser_v2.py
fix: use volume storage instead of water storage
=> fix: use volume storage instead of water storage

src/bthome_ble/parser.py, tests/test_parser_v2.py
I have a Shelly device with a buggy firmware which constantly log this message:
```
BTHome device is not sending object ids in numerical order (from low to high object id). This can cause issues with your BTHome receiver, payload: 008a016445c40005e02e002101
```
The message doesn't help identifying the device (although I know it is one of two devices) and in use case of multiple devices it would be hard to identify which device is logging the message and may be confusing when trying to analyze logs.
Added device title where it is possible and added/modified tests to cover the log messages
=> feat: add device title to log messages

src/bthome_ble/parser.py, tests/test_parser_v2.py
feat: allow one failed decryption before reauth
fix for #107
=> feat: allow one failed decryption before reauth

src/bthome_ble/parser.py
Minimal version of fix for #116.
=> fix: accept new encryption counter only if the message was not corrupted

src/bthome_ble/const.py, tests/test_parser_v2.py
Added property 'direction' 0x5E, in degrees, precision: 0.01, 2 bytes unsigned
Added property 'precipitation' 0x5F in mm, precision: 1, 2 bytes unsigned
Related document change:
[Document change](https://github.com/home-assistant/bthome.io/pull/53)
=> feat(bthome): add direction and precipitation support

src/bthome_ble/const.py, tests/test_parser_v2.py
The use of new type "Channel" is to allow sensor data from multiple arrays of identical sensors to be transmitted
=> feat (bthome): Add channel data type

src/bthome_ble/parser.py
(fix): use little endian in float conversion (fix #143)
=> fix: use little endian in float conversion

.github/workflows/ci.yml
[python-semantic-release/upload-to-gh-release](https://github.com/python-semantic-release/upload-to-gh-release) has been retired and replaced with [python-semantic-release/publish-action](https://github.com/python-semantic-release/publish-action)
additionally we have trusted publishing set up now so the token is no longer needed and can be deleted.
=> fix: replace python-semantic-release/upload-to-gh-release with python-semantic-release/publish-action

src/bthome_ble/parser.py
fix: remove errors while parsing timestamp
Fixes an error reported on the HA forum https://community.home-assistant.io/t/bthome-discussion-topic/504361/51
=> fix: remove errors while parsing timestamp

src/bthome_ble/bthome_v1_encryption.py, src/bthome_ble/bthome_v2_encryption.py, src/bthome_ble/parser.py, tests/test_parser_v2.py, tests/test_v2_encryption.py
- fix: encrypted data is checked for its length, but two bytes data (like binary sensors) were marked as invalid due the the length check. This has been fixed (fix #254)
- fix: new shelly devices are now being detected correctly (fix #215)
=> fix: encryption length check
